blogging/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from ourblog import views as ourblog_views
from ourblog import models
from django.contrib.auth.views import login

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', ourblog_views.home, name="home"),
    url(r"blog/(\d+)/$", ourblog_views.blog, name="individual_blog"),
    url(r"create_blog/$", ourblog_views.create_blog, name="create_blog"),
    url(r"create_blogger/$", ourblog_views.create_blogger, name="create_blogger"),
    url(r"like/(\d+)/$", ourblog_views.like_blog, name="like_blog"),
    url(r"add_comment/(\d+)/", ourblog_views.add_comment, name="add_comment"),

    #account logins
    url(r"^login/$", login, {"template_name":"account/login.html"}),
    url(r"^account/login/$", ourblog_views.login, name="login"),
    url(r"^account/auth$", ourblog_views.auth_view, name="auth_view"),
    url(r"^account/logout/$", ourblog_views.logout, name="logout"),
    url(r"^account/loggedin/$", ourblog_views.loggedin, name="loggedin"),
    url(r"^account/invalid/$", ourblog_views.invalid_login, name="invalid_login"),
    #Acoount registrations
    url(r"^account/register/$", ourblog_views.register_user, name="register_user"),
    url(r"^account/register_success/$", ourblog_views.register_success, name="register_success"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ourblog/models.py
from __future__ import unicode_literals
from django.db import models
from PIL import Image
from time import time

def upload_blog_image(instance, filename):
    return "blog_content_image/%s_%s" % (str(time()).replace(".", "_"), filename)

def profile_image(instance, filename):
    return "profile_image/%s_%s" % (str(time()).replace(".", "_"), filename)

# Create your models here.
class Blogger(models.Model):
    UNIVERSITIES = (
        ("JKUAT", 'Jommo Kenyatta University of Agriculture and technology'),
        ('UON', 'University of Nairobi'),
        ('KU', 'Kenyatta University'),
        ("STRATH", "Strathmore"),
        ("DAYSTAR", "Daystat University"),
        ("CUEA", "Cooperative University of East Africa"),
    )
    PLACE = (
        ("Juja", "Juja"),
        ("Nairobi","Nairobi"),
        ("Kahawa","Kahawa"),
        ("Madaraka","Madaraka"),
        ("Athi-River","Athi-River"),
        ("Karen","Karen")
    )
    name = models.CharField(max_length=120, null=False)
    info = models.TextField("Profile bio", blank=True, null=True)
    profile_image = models.FileField(upload_to=profile_image, null=False, blank=True)
    place_from = models.TextField("Place from", choices=PLACE, max_length=1, null=False, blank=True)
    university_name = models.TextField("University from", max_length=1, choices=UNIVERSITIES, null=True, blank=True)
    course_name = models.CharField("Course undertaking",max_length=150, null=True, blank=True)

    def __str__(self):
        return self.name

class Blog(models.Model):
    Category = (
        ("Travelling","Travelling"),
        ("Work","Work"),
        ("Lifestyle","Lifestyle"),
        ("Photography","Photography"),
        ("Finance","Finance"),
        ("Programming","Programming"),
        ("Food & Drinks","Food & Drinks"),
        ("Technology","Technology"),
        ("Engineering","Engineering"),
        ("Science","Science"),
        ("Law","Law"),
        ("Health","Health"),
        ("Agriculture","Agriculture"),
        ("Enterprenuership","Enterprenuership"),
        ("Cars", "Cars"),
    )
    title = models.CharField(max_length=120, null=False)
    blog_text = models.TextField(blank=False, null=False)
    blog_image = models.FileField(upload_to=upload_blog_image, null=True, blank=True)
    category = models.TextField(choices=Category, max_length=5, null=True, blank=False)
    publish_date = models.DateTimeField("Date published", null=True)
    likes = models.IntegerField(default=0)
    blogger = models.ForeignKey(Blogger, on_delete=models.DO_NOTHING , null=False)

    def __str__(self):
        return self.title

class Comment(models.Model):
    name = models.CharField(max_length=100)
    body = models.TextField(blank=False)
    publish_date = models.DateTimeField("Date published")
    blog = models.ForeignKey(Blog, on_delete=models.DO_NOTHING,null=False)

templates/add_comment.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% block content %}

<main class="main pt-4" role="main">
  <div class="container">
    <div class="row">
    <div class="col-md-9">
      <form action="{% url "add_comment" blog.id %}" method="post">{% csrf_token %}
        <ul>
          {{ form.as_ul }}
        </ul>
        <input type="submit" name="submit" value="Post Comment">
      </form>
      </div>
      {% include "aside_create.html" %}
  </div>
</div>
</main>
{% endblock %}

templates/aside.html
{% load static %}
{% load staticfiles %}
<div class="col-md-3 ml-auto">
<aside class="sidebar">
  <div class="card mb-4">
    <div class="card-body">
      <h4 class="card-title">About</h4>
      <p class="card-text">Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam <a href="">semper libero</a>, sit amet adipiscing sem neque sed ipsum. </p>
    </div>
  </div><!-- /.card -->
</aside>
<aside class="sidebar sidebar-sticky">
  <div class="card mb-4">
    <div class="card-body">
      <h4 class="card-title">Tags</h4>
          <a class="btn btn-light btn-sm mb-1" href="" >Travelling</a>
          <a class="btn btn-light btn-sm mb-1" href="" >Work</a>
          <a class="btn btn-light btn-sm mb-1" href="" >Lifestyle</a>
          <a class="btn btn-light btn-sm mb-1" href="" >Photography</a>
          <a class="btn btn-light btn-sm mb-1" href="" >Finance</a>
          <a class="btn btn-light btn-sm mb-1" href="" >Programming</a>
          <a class="btn btn-light btn-sm mb-1" href="" >Food &amp; Drinks</a>
          <a class="btn btn-light btn-sm mb-1" href="" >Technology</a>
          <a class="btn btn-light btn-sm mb-1" href="" >Engineering</a>
          <a class="btn btn-light btn-sm mb-1" href="" >Science</a>
          <a class="btn btn-light btn-sm mb-1" href="" >Law</a>
          <a class="btn btn-light btn-sm mb-1" href="" >Health</a>
          <a class="btn btn-light btn-sm mb-1" href="" >Agriculture</a>
          <a class="btn btn-light btn-sm mb-1" href="" >Enterprenuership</a>
          <a class="btn btn-light btn-sm mb-1" href="" >Cars</a>
    </div>
  </div><!-- /.card -->
  <div class="card mb-4">
    <div class="card-body">
      <h4 class="card-title">Popular stories</h4>
      
      <a href="" class="d-inline-block">
        <h4 class="h6">The blind man</h4>
        <img class="card-img" src="{% static "/img/2.jpg" %}" alt="">
      </a>
      <time class="timeago" datetime="2017-10-03 20:00" data-tid="7">7 months ago</time> in Lifestyle
      <a href="" class="d-inline-block mt-3">
        <h4 class="h6">Crying on the news</h4>
        <img class="card-img" src="{% static "/img/3.jpg" %}" alt="">
      </a>
      <time class="timeago" datetime="2017-07-16 20:00" data-tid="8">10 months ago</time> in Work
    </div>
  </div><!-- /.card -->
</aside>
</div>

templates/aside_create.html
{% load static %}
{% load staticfiles %}
<div class="col-md-3 ml-auto">
<aside class="sidebar">
  <div class="card mb-4">
    <div class="card-body">
      <h4 class="card-title">About</h4>
      <p class="card-text">Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam <a href="">semper libero</a>, sit amet adipiscing sem neque sed ipsum. </p>
    </div>
  </div><!-- /.card -->
</aside>
<aside class="sidebar sidebar-sticky">
  <div class="card mb-4">
    <div class="card-body">
      <h4 class="card-title">Popular stories</h4>
      <a href="" class="d-inline-block">
        <h4 class="h6">The blind man</h4>
      </a>
      <a href="" class="d-inline-block mt-3">
        <h4 class="h6">Crying on the news</h4>
      </a>
    </div>
  </div><!-- /.card -->
</aside>
</div>

templates/base.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Where we connect university by blogging">
  <meta name="author" content="Rodney Osodo">
  <link rel="icon" href="{% static "/img/favicon.png" %}">
  <title>Unify</title>

  <link href="{% static "/css/milo.css" %}" rel="stylesheet">
</head>
<body>
  {% include "header.html" %}
  {% block content %}
  {% endblock %}
  {% include "footer.html" %}
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="{% static "/javascript/bundle.js" %}"></script>
</body>
</html>

templates/create_blog.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% block content %}

<main class="main pt-4" role="main">
  <div class="container">
    <div class="row">
    <div class="col-md-9">
      <form class="" action="{% url "create_blog" %}" method="post">{% csrf_token %}
        <ul>
          <li>
          	<label for="id_title">Title:</label>
          	<input type="text" name="title" id="id_title" maxlength="120" required />
          </li>
          <li>
          	<label for="id_blog_text">Blog text:</label>
			<textarea name="blog_text" rows="10" id="id_blog_text" required cols="40"></textarea>
		  </li>
		  <li>
				<label for="id_blog_image">Blog image:</label>
				<input type="file" name="blog_image" id="id_blog_image" />
		  </li>
        </ul>
        <input type="submit" name="submit" value="Create Blog">
      </form>
      </div>
      {% include "aside_create.html" %}
  </div>
</div>
</main>
{% endblock %}

templates/create_blogger.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% block content %}

<main class="main pt-4" role="main">
  <div class="container">
    <div class="row">
    <div class="col-md-9">
      <form class="" action="{% url "create_blogger" %}" method="post">{% csrf_token %}
        <ul>
			<li>
				<label for="id_name">Name:</label>
				<input type="text" name="name" id="id_name" maxlength="120" required />
			</li>
			<li>
				<label for="id_info">Profile bio:</label>
				<textarea name="info" rows="10" id="id_info" cols="40"></textarea>
			</li>
			<li>
				<label for="id_profile_image">Profile image:</label>
				<input type="file" name="profile_image" id="id_profile_image" />
			</li>
			<li>
				<label for="id_place_from">Place from:</label>
				<select name="place_from" id="id_place_from">
			  		<option value="" selected>---------</option>
			 		<option value="Juja">Juja</option>
					  <option value="Nairobi">Nairobi</option>
					  <option value="Kahawa">Kahawa</option>
					  <option value="Madaraka">Madaraka</option>
					  <option value="Athi-River">Athi-River</option>
					  <option value="Karen">Karen</option>
				</select>
			</li>
			<li>
				<label for="id_university_name">University from:</label>
				<select name="university_name" id="id_university_name">
			  		<option value="" selected>---------</option>
					<option value="JKUAT">Jommo Kenyatta University of Agriculture and technology</option>
					<option value="UON">University of Nairobi</option>
					<option value="KU">Kenyatta University</option>
					<option value="STRATH">Strathmore</option>
					<option value="DAYSTAR">Daystat University</option>
					<option value="CUEA">Cooperative University of East Africa</option>
				</select>
			</li>
			<li>
				<label for="id_course_name">Course undertaking:</label>
				<input type="text" name="course_name" id="id_course_name" maxlength="150" />
			</li>
        </ul>
        <input type="submit" name="submit" value="Create Blogger">
      </form>
      </div>
      {% include "aside_create.html" %}
  </div>
</div>
</main>
{% endblock %}

templates/footer.html
<footer class="site-footer bg-darkest" role="contentinfo">
  <div class="container">

    <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link" href="">Privacy policy</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">Terms</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">Feedback</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">Advertise</a>
      </li>
    </ul>
    <div class="copy">
      © Unify 2018<br>
      All rights reserved
    </div>
  </div>
</footer>

templates/header.html
<header role="banner">
  <nav class="navbar navbar-expand-md navbar-light bg-white absolute-top">
    <div class="container">
      <button class="navbar-toggler order-2 order-md-1" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse order-3 order-md-2" id="navbar">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown active">
            <a class="nav-link"  href="{% url "home" %}">Home</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Category</a>
            <div class="dropdown-menu" aria-labelledby="dropdown03">
              <a class="dropdown-item" href="">Typography</a>
              <a class="dropdown-item" href="">Buttons</a>
              <a class="dropdown-item" href="">Tables</a>
              <a class="dropdown-item" href="">Forms</a>
              <a class="dropdown-item" href="">Cards</a>
            </div>
          </li>
        </ul>
      </div>
      <a class="navbar-brand mx-auto order-1 order-md-3" href="">Unify</a>
      <div class="collapse navbar-collapse order-4 order-md-4" id="navbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="">About</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
            <div class="dropdown-menu" aria-labelledby="dropdown03">
              {% if user.is_authenticated %}
              <a class="dropdown-item" href="{% url "logout" %}">Logout</a>
              {% else %}
              <a class="dropdown-item" href="{% url "register_user" %}">Register User</a>
              <a class="dropdown-item" href="{% url "login" %}">Login</a>
              {% endif %}
            </div>
          </li>
        </ul>
        <form class="form-inline" role="search">
          <input class="search js-search form-control form-control-rounded mr-sm-2" type="text" title="Enter search here.." placeholder="Search.." aria-label="Search">
        </form>
      </div>
    </div>
  </nav>
</header>

templates/home.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Where we connect university by blogging">
  <meta name="author" content="Rodney Osodo">
  <link rel="icon" href="{% static "/img/favicon.png" %}">
  <title>Unify</title>

  <link href="{% static "/css/milo.css" %}" rel="stylesheet">
</head>
<body>
  {% include "header.html" %}
  {% block content %}
  {% endblock %}
  {% include "homemain.html" %}
  {% include "footer.html" %}
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="{% static "/javascript/bundle.js" %}"></script>
</body>
</html>

templates/homemain.html
{% load static %}
{% load staticfiles %}
{% block content %}
<main class="main pt-4" role="main">

  <div class="container">

    <div class="row">
      <div class="col-md-4">

        <article class="card mb-4">
          <header class="card-header">
            <div class="card-meta">
              <a href=""><time class="timeago" datetime="2017-10-26 20:00" data-tid="1">6 months ago</time></a> in <a href="">Journey</a>
            </div>
            <a href="">
              <h4 class="card-title">How can we sing about love?</h4>
            </a>
          </header>
          <a href="">
            <img class="card-img" src="{% static "/img/18.jpg" %}" alt="">
          </a>
          <div class="card-body">
            <p class="card-text">Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. </p>
          </div>
        </article><!-- /.card -->
      </div>
      <div class="col-md-4">
        {% for blog in blogs %}
        <article class="card mb-4">
          <header class="card-header">
            <div class="card-meta">
              <a href=""><time class="timeago" data-tid="4">{{ blog.publish_date }}</time></a> in <a href="">Lifestyle</a>
            </div>
            <a href="{% url "individual_blog" blog.id %}">
              <h4 class="card-title">{{ blog.title }}</h4>
            </a>
          </header>
          {% if blog.blog_image %}
          <a href="{% url "individual_blog" blog.id %}">
            <img class="card-img" src="{{ blog.blog_image.url }}" alt="">
          </a>
          {% endif %}
          <div class="card-body">
            <p class="card-text">{{ blog.blog_text|truncatewords:20 }}</p>
            <p>{{ blog.likes }} people liked this article</p>
          </div>
        </article><!-- /.card -->
        {% endfor %}
      </div>
      {% include "aside.html" %}
    </div>
  </div>
</main>
<div class="container">
  {% if blogs.has_previous %}
  <a href="?page=1">&laquo; first</a>
  <a href="?page={{ blogs.previous_page_number }}">previous</a>
  {% endif %}
  Page {{ blogs.number }} of {{ blogs.paginator.num_pages }}
  {% if blogs.has_next %}
    <a href="?page={{ blogs.next_page_number }}">next</a>
    <a href="?page={{ blogs.paginator.num_pages }}">last &raquo;</a>
  {% endif %}
</div>
{% endblock %}

templates/individual_blog.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% block content %}
<main class="main pt-4" role="main">
  <div class="container">
    <div class="row">
    <div class="col-md-9">
        <article class="card mb-4">

          <header class="card-header">
            <div class="card-meta">
              <time class="timeago">{{ blog.publish_date }}</time> in <a href="">Lifestyle</a>
            </div>
            <a href="">
              <h4 class="card-title">{{ blog.title }}</h4>
            </a>
          </header>
          {% if blog.blog_image %}
          <a href="">
            <img class="card-img" src="{{ blog.blog_image.url }}" width="426px" height="624px%">
          </a>
          {% endif %}
          <div class="card-body">
            <p class="card-text">{{ blog.blog_text }}</p>
            <p>{{ blog.likes }} people liked this article</p>
            <p> <a href="{% url "like_blog" blog.id %}">Like</a></p>
          </div>
          <h2>Comments</h2>
          {% for c in blog.comment_set.all %}
          <p>{{ c.name }} :</p><p>{{ c.body }}</p>
          {% endfor %}
          <p> <a href="{% url "add_comment" blog.id %}">Add Comment</a> </p>
        </article>
      </div>
      {% include "aside.html" %}
  </div>
</div>
</main>
{% endblock %}